name: HealthIndicator
author: Nathan_N
version: 1.0
description: This plugin shows the health of other players in specified worlds below their name
website: https://www.spigotmc.org/resources/30196/
main: com.github.nathannr.healthindicator.HealthIndicator
commands:
  healthindicator:
    description: Information about the plugin or reload the plugin
    usage: /<command> [reload]
    aliases: [hi, damageindicator, di]
permission:
  healthindicator.*:
    description: HealthIndicator permission
  healthindicator.reload:
    description: Allows you to reload the plugin
    default: OP